/**
 * 유저 관리 페이지
 *
 * @author 김이안
 */
import Head from 'next/head';
import { PageOptions, ResponsiveLayout, Search } from '../../../components';
import { Flex } from '@chakra-ui/react';
import { useSafePush } from '../../../hooks';
import UserPageContainer from '@/containers/system/user-management/UserPageContainer';
import { UsersUtils } from '@/containers';

const UserManagementPage = () => {
  const { router, push } = useSafePush();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveLayout>
        <Flex direction={'column'} gap={'4'} h={'100%'}>
          <UsersUtils />
          <Flex justifyContent={'space-between'} gap={'4'} wrap={'wrap'}>
            <Search
              onSubmit={(search) =>
                push({
                  pathname: router.pathname,
                  query: { ...router.query, search },
                })
              }
            />
            <Flex gap={'4'}>
              <PageOptions />
            </Flex>
          </Flex>
          <UserPageContainer />
        </Flex>
      </ResponsiveLayout>
    </>
  );
};

export default UserManagementPage;
