import { useGetEmpire } from '@/apis';
import { ResponsiveLayout } from '@/components';
import { EmpireCard } from '@/containers';
import { QueryParser } from '@/utils';
import Head from 'next/head';
import { useRouter } from 'next/router';

const EmpirePage = () => {
  const router = useRouter();
  const { data: empire } = useGetEmpire(QueryParser.toNumber(router.query.id));

  console.log(empire);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveLayout>
        <EmpireCard data={empire} />
      </ResponsiveLayout>
    </>
  );
};

export default EmpirePage;
