import { useGetOneWorld } from '@/apis';
import { ResponsiveLayout } from '@/components';
import { OneWorldCard } from '@/containers';
import { QueryParser } from '@/utils';
import Head from 'next/head';
import { useRouter } from 'next/router';

const OneWorldPage = () => {
  const router = useRouter();
  const { data: oneWorld } = useGetOneWorld(QueryParser.toNumber(router.query.id));

  console.log(oneWorld);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveLayout>
        <OneWorldCard data={oneWorld} />
      </ResponsiveLayout>
    </>
  );
};

export default OneWorldPage;
