import Head from 'next/head';

const GaiaHead = () => {
  return (
    <Head>
      <title>GAIA Athometrip</title>
      <meta name="description" content="Generated by Athometrip IT Team Developers" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default GaiaHead;
